url: "https://notes.zemmyang.com" # the base hostname & protocol for your site, e.g. http://example.com

# If you want to install this jekyll in a subpath (eg /digitalgarden) set it here. 
# Else keep it Empty (DON'T PUT /; Keep it empty)
baseurl: ""

# Website Header, Description, Footer year and text. 
# If you are deleting this, make sure you remove it from HTML files too 
heading: zeNotes
content: I also write stuff
copyright:  
  year: 2023
  msg: Insert Footnote Here

# Set title and content for private & broken link tooltop
privatelinks:
  title: Private or Broken Links
  msg: The page you're looking for is either not available or private!

# Theme level preferences
# To enable set "enabled : true" else, use "enabled:false"
preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true
# To enable a homepage, change the value to true and add content to _includes/Homepage.html
# If enable : false, notes feed will be as homepage. 
  homepage: 
    enabled: false ##If you need a homepage, change this to true and edit _includes/Homepage.html

encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-tidy
    
## Enable Collections
## Suggested collects are "notes" "lists" and "blog"
collections:
    notes:
      output: true
      permalink: /:title

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /post/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: Post
      content-type: notes


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _notes/Drafts
  - _notes/Templates
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/